### ISSUE TITLE
Problème avec :attribute

### ISSUE THREAD

**Issue by MIMIGAMING83** [Umbo-France/Traduction#5]
Hier j'ai commencé les traductions, Mr Games c'est chargé de mettre les traductions sur le site, mais il y a un problème, :attribute est sensé être une variable, changé par la suite, mais dans ma capture d'écran, il n'est pas changé, regardez un exemple Le champ :attribute est requis. renvoie https://i.imgur.com/Hlftrj9.png sur le site

**Comment by MrGameMemo** [comment]
À voir avec Fristel sur Discord.

**Comment by UmboFrance** [comment]
Hey,
Je vais voir cela pour les attribute, je laisse l'issue ouvert tant que ses pas réglé !

Je vous tient au courant sur cette issue

**Comment by MrGameMemo** [comment]
Je crois avoir réglé le problème : il s'agissait d'une faute de frappe lors d'une apostrophe, considérée comme un début de string (oubli du \).

En attente de tests qui confirmeront ma suspicion.

**Comment by MIMIGAMING83** [comment]
Le problème n'est toujours pas réglé, je viens d'aller voir sur mon panel umbo à l'instant 12:13:30~

**Comment by MIMIGAMING83** [comment]
Normalement :attribute = quelque-chose
Mais la
:attribute != Quelque-chose
:attribute = ∅

**Comment by MIMIGAMING83** [comment]
Après c'est peut être que il ne faut pas utiliser les apostrophes, exemple si c'est comme en js, il faudra faire `Le champ ${attribute} est requis.` après je sais pas comment ça marche en php, je n'y ai jamais touché, cette traduction sera la première fois à laquelle je touche à un fichier ".php"

**Comment by MIMIGAMING83** [comment]
\`Le champ ${attribute} est requis.\`

**Comment by UmboFrance** [comment]
Cela à été résolut, je ferme cette issue

**Comment by MIMIGAMING83** [comment]
Mettre l'issue en solved m'aurai semblé plus correct ;)

**Comment by MrGameMemo** [comment]
Je fais ça de suite.

**Comment by MrGameMemo** [comment]
Ce n’est pas possible de le faire. On ne peut que la fermer, pas grave...

**Comment by MIMIGAMING83** [comment]
Pas grave, il me semblait que s'était possible :thinking: bref ^^
